### ISSUE TITLE
release version parity

### ISSUE THREAD

**Issue by bdolor** [lumenlearning/candela-citation#4]
The version number of composer.json 

- https://github.com/lumenlearning/candela-citation/blob/master/composer.json#L5

based on the version number of the plugin 

- https://github.com/lumenlearning/candela-citation/blob/master/candela-citation.php#L6

should match the release version on github 

- https://github.com/lumenlearning/candela-citation/releases/tag/1.0.0

Otherwise composer can't find the release: 

![image](https://user-images.githubusercontent.com/2048170/30576071-0e517306-9cba-11e7-8020-55d248c7421f.png)

and small, fluffy white kittens cry. 😹

**Comment by ghost** [comment]
Haha!  Sorry about the fluffy white kitten.  First time managing releases.  Thanks for the heads up!

**Comment by ghost** [comment]
Looks like it's working for me now.  Here's what my `composer.json` looks like for my test case:

```
{
        "repositories": [
                {
                        "type": "vcs",
                        "url": "https://github.com/lumenlearning/candela-citation"
                }
        ],
        "require": {
                "lumenlearning/candela-citation": "1.0.0"
        }
}
```
Can you confirm it's working for you @bdolor?

**Comment by bdolor** [comment]
yay 
![image](https://user-images.githubusercontent.com/2048170/30616049-c7c32b82-9d45-11e7-8219-d94b44aa27d8.png)
